/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class game_Game */

#ifndef _Included_game_Game
#define _Included_game_Game
#ifdef __cplusplus
extern "C" {
#endif
#undef game_Game_COLUMNS
#define game_Game_COLUMNS 5L
#undef game_Game_ROWS
#define game_Game_ROWS 5L
#undef game_Game_FIELDS
#define game_Game_FIELDS 25L
#undef game_Game_TO_WIN
#define game_Game_TO_WIN 4L
/*
 * Class:     game_Game
 * Method:    nextMove
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_game_Game_nextMove
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
